package:
  name: konstan-testi
  version: 0.8.17

source:
  path: .

build:
  number: 0
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
  run:
    - python
    - cython
    - numpy
    - scipy